name: FACELY
options:
  createIntermediateGroups: true
  bundleIdPrefix: ar.com.rostrolocal
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.10"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "0.1.0"
    CLANG_ENABLE_MODULES: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  FACELY:
    type: application
    platform: iOS
    sources:
      - path: FACELY
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ar.com.rostrolocal.facely
        PRODUCT_NAME: FACELY
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: FACELY
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - sdk: libsqlite3.tbd
    scheme:
      testTargets:
        - FACELYTests

  FACELYTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FACELYTests
    dependencies:
      - target: FACELY
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ar.com.rostrolocal.facely.tests
        GENERATE_INFOPLIST_FILE: YES
